spring:
  datasource:
    druid:
      # 驱动类
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据库url
      url: jdbc:mysql://localhost:3306/db_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
      # 数据库登录名
      username: root
      # 数据库登录密码
      password: lyc-2012
      # 最大等待时间
      max-wait: 6000
      # 最大连接数
      max-active: 30
      # 初始化时建立物理连接
      initial-size: 5
      # 最小连接数
      min-idle: 5

